// Code generated by weaver; DO NOT EDIT.
//
// Internal semantic convention constants generated from registry/model.
// Regenerate with: registry/weaver.sh generate
package semconv

import "go.opentelemetry.io/otel/attribute"

// ComExampleDeliveryCarrier is the attribute key for "com.example.delivery.carrier".
// Brief: Identifier of the delivery carrier.
var ComExampleDeliveryCarrier = attribute.Key("com.example.delivery.carrier")

// ComExampleDeliveryId is the attribute key for "com.example.delivery.id".
// Brief: Unique identifier of a delivery.
var ComExampleDeliveryId = attribute.Key("com.example.delivery.id")
